# -*- coding: utf-8 -*-
"""translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlP4FrjLmupBvJb3zmck0_ut0eUWMS3o
"""

!pip install streamlit
!pip install transformers

import streamlit as st
from transformers import MarianTokenizer, MarianMTModel

# Commented out IPython magic to ensure Python compatibility.
# #open file with pyhton extention
# %%writefile translation_file.py
# import streamlit as st
# from transformers import MarianTokenizer, MarianMTModel
# def main():
# 
#     st.title("Text Translation App")
# 
#     # Load the translation model
#     from transformers import MarianTokenizer, MarianMTModel
#     model_name = "marefa-nlp/marefa-mt-en-ar"
#     translator = MarianMTModel.from_pretrained(model_name)
#     tokenizer = MarianTokenizer.from_pretrained(model_name)
# 
# 
#     # Text input
#     text_input = st.text_area("Enter English text to translate  into Arabic:", height=200)
# 
# 
#     # translation button
#     if st.button("Translate"):
#         if text_input:
#             # Tokenize input text
#             input_ids = tokenizer(text_input, return_tensors="pt", padding=True, truncation=True)["input_ids"]
#             # Perform translation
#             translated_ids = translator.generate(input_ids, max_length=150, min_length=30, do_sample=False)
#             translated_text = tokenizer.decode(translated_ids[0], skip_special_tokens=True)
#             st.subheader("Translate:")
#             st.write(translated_text)
#         else:
#             st.warning("Please enter some text to translate.")
# 
# # Run the Streamlit app
# if __name__ == "__main__":
#     main()
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
#

#generate address
! wget -q -O - ipv4.icanhazip.com

#run streamlit then copy url and copy address in the above cell
#finally you can see your website
! streamlit run translation_file.py & npx localtunnel --port 8501